[package]
name = "cvr-i18n"
version = "0.1.0"
edition = "2024"
authors = ["Tunglies"]
license-file = "LICENSE"

[dependencies]
clap = "4.5.51"
serde_json = "1.0"
indexmap = { version = "2.12.0", features = ["serde"] }

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "z"